### ISSUE TITLE
Throws when search contains '\'

### ISSUE THREAD

**Issue by janmyler** [helior/react-highlighter#17]
Hi, I send string values into `search` prop, but it throws (e.g. `Uncaught SyntaxError: Invalid regular expression: /hello wor\/: \ at end of pattern`) when the user enters backslash '\'.

What would be the correct way of handling this, inside or outside of the component?

**Comment by pke** [comment]
Since the component expects a valid regex object it should be handled outside the component.

**Comment by janmyler** [comment]
Hmm this is speculative. `search` prop has following property type:
```
search: React.PropTypes.oneOfType([
  React.PropTypes.string,
  React.PropTypes.number,
  React.PropTypes.bool,
  RegExpPropType
]).isRequired,
```

And then there is:
```
getSearch: function() {
    if (this.props.search instanceof RegExp) {
      return this.props.search;
    }

    var flags = '';
    if (!this.props.caseSensitive) {
      flags +='i';
    }

    return new RegExp(this.props.search, flags);
  }
```
If there's any string (not a regex) converted to a regex instance, it should be imo handled internally somehow and not throwing outside of the component.

**Comment by pke** [comment]
Good point. I also wonder what kind of `RegExp` would be created from a `search` number or bool?
