### ISSUE TITLE
Cannot apply unknown props to html elements.

### ISSUE THREAD

**Issue by canfie1d** [helior/react-highlighter#32]
In React 15.1.0 I am getting this warning in the console:

```Warning: Unknown props `search`, `caseSensitive`, `matchElement`, `matchClass`, `matchStyle` on <span> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop```

This occurs from applying non standard props to an HTML element. i.e. `<span search='string'>`.

Thanks for your work on this project. 🙇

**Comment by helior** [comment]
Hey @canfie1d https://github.com/helior/react-highlighter/pull/30 should resolve your issue.

**Comment by canfie1d** [comment]
Thanks!
