### ISSUE TITLE
Suppress new React deprecation warnings

### ISSUE THREAD

**Issue by gnestor** [helior/react-highlighter#38]
React will be removing `createClass` and `PropTypes` in React 16.

![image](https://cloud.githubusercontent.com/assets/512354/25533731/6e7cc0e0-2be6-11e7-84dd-b30d133c7540.png)

"Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead."

"Warning: Highlighter: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement."

**Comment by helior** [comment]
I believe this issue has been resolved by #39 and #37.
