### ISSUE TITLE
Publish UMD files generated by Webpack

### ISSUE THREAD

**Issue by nickmccurdy** [helior/react-highlighter#40]
The npm package does not include any browser-friendly UMD builds because the `dist` directory is missing from `files` in `package.json`.

Instructions to fix (see suggested workflow): https://unpkg.com/

**Comment by treetrum** [comment]
+1 for this

**Comment by helior** [comment]
Nice tip @nickmccurdy! Here are the result URLs:
* https://unpkg.com/react-highlighter@0.4.0/dist/ReactHighlighter-v0.4.0.min.js
* https://unpkg.com/react-highlighter@0.4.0/dist/ReactHighlighter-v0.4.0.js
