### ISSUE TITLE
make `create-react-class` and `prop-types` as runtime dependencies

### ISSUE THREAD

**Issue by nachikethashu** [helior/react-highlighter#41]
as per https://github.com/helior/react-highlighter/commit/ec2ae091898ac666a184a9b102484cc1c6d71543 `create-react-class` and `prop-types` are declared as `devDependencies` which leads to errors if we have our own build-system instead of npm which just relies on run time dependencies.

**Comment by lpommers** [comment]
We're seeing this as well in our build system; would greatly appreciate. 🙇
