### ISSUE TITLE
getDefaultProps usage

### ISSUE THREAD

**Issue by mvolkmann** [helior/react-highlighter#44]
I get lots of these warnings in the browser dev tools console:

Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named defaultProps instead.

It would be great if this library could be updated to not use getDefaultProps.
I see this is on line 24 of https://github.com/helior/react-highlighter/blob/master/lib/highlighter.js.

**Comment by ericgio** [comment]
Submitted #45 to address this and another warning.

**Comment by helior** [comment]
Thanks @mvolkmann, @ericgio. This issue is ready to be closed.
