### ISSUE TITLE
Deprecation warning for React.DOM.span

### ISSUE THREAD

**Issue by derwaldgeist** [helior/react-highlighter#48]
I'm using https://github.com/ericgio/react-bootstrap-typeahead which depends on your module. Since I added it, I noticed a deprecation warning which I could track down to `react-highlighter`:

> Warning: Accessing factories like React.DOM.span has been deprecated and will be removed in v16.0+. Use the react-dom-factories package instead.  Version 1.0 provides a drop-in replacement. For more info, see https://fb.me/react-dom-factories

This is caused by this line:
https://github.com/helior/react-highlighter/blob/7abda7dcb8b770121d04df9e231c0433df460491/lib/highlighter.js#L177

Would be great if this could be fixed. Thanks and keep up the good work!

**Comment by ericgio** [comment]
I submitted #45 to address this issue. @helior, would be great to merge that whenever you get a chance.

**Comment by dceddia** [comment]
This is broken in React 16. Here's the error I'm getting:

![image](https://user-images.githubusercontent.com/505704/30877152-dc539ce0-a2c6-11e7-8504-1d21c969b605.png)

It looks like the PR #45 fixes it though. Any idea when that'll be merged?

**Comment by helior** [comment]
@dceddia @ericgio @derwaldgeist #45 was merged this morning, along with additional fixes. Thanks for calling this out!

**Comment by derwaldgeist** [comment]
Thanks!
