### ISSUE TITLE
[PropTypes] Allow React components for matchElement

### ISSUE THREAD

**Issue by kachkaev** [helior/react-highlighter#55]
Hi @helior and many thanks for your library! With `react-highlighter` I got from _zero_ to _all done_ in just 10 minutes, which is mind-blowing even in the React world!

I'm writing to share a minor issue I've faced when using `<Highlight />` together with [`styled-components`](https://www.styled-components.com/). Here's my code:

```jsx
import styled from "styled-components";

const HighlightMark = styled.span`
  background: rgba(255, 255, 0, 0.3);
  border-radius: 4px;
  display: inline-block;
  margin: auto -3px;
  padding: 0 3px;
`;

// ... 

<Highlight search={highlightRegexp || false} matchElement={HighlightMark}>
  {text}
</Highlight>

``` 

This produces a warning in development environment:

```
Warning: Failed prop type: Invalid prop `matchElement` of type `function` supplied to `Highlighter`, expected `string`.
```

It'd be great if `matchElement` in PropTypes allowed using custom react components in addition to strings. The issue is only with the warning – all working great apart from that 🎉

**Comment by kachkaev** [comment]
@helior would you be happy to release a new patch version if I submit a PR?

**Comment by helior** [comment]
Hi @kachkaev, I'm glad to hear you were up in running so quickly 👍 . This is a great idea to define components for the matching element. If you have a PR, I would be happy to release a version with the new feature.

**Comment by kachkaev** [comment]
Here you go: #56 🙌 

Looking forward for a new patch release! 😉
